---

- hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:

  - name: Update apt cache
    apt: upgrade=yes update_cache=yes
    when: ansible_os_family == 'Debian'

  tasks:

    - include_vars: defaults/main.yml

    - include_vars: test_vars.yml

    - include: tasks/main.yml

    - name: restart httpd
      sudo: yes
      when: ansible_os_family == 'Debian'
      service: name=apache2
               state=restarted

    - name: restart httpd
      sudo: yes
      when: ansible_os_family == 'RedHat'
      service: name=httpd
               state=restarted

    - name: Check to see if apache is running
      uri:
        url: http://127.0.0.1:80/
        method: GET
        status_code: 200, 403

    - name: Check to see if apache shib2 module is loaded
      uri:
        url: https://127.0.0.1:443/Shibboleth.sso/Status
        method: GET
        status_code: 200
        validate_certs: no
      when: ansible_os_family == 'Debian'

  handlers:
    - include: handlers/main.yml
