---

- hosts: all
  sudo: yes
  gather_facts: yes

  tasks:

    - include_vars: defaults/main.yml

    - include_vars: test_vars.yml

    - include: tasks/main.yml

    - name: restart httpd
      sudo: yes
      service: name=apache2
               state=restarted

  handlers:
    - include: handlers/main.yml
