- name: Install apache2 and shibboleth module
  sudo: yes
  when: ansible_os_family == 'Debian'
  apt: pkg={{ item }} state=present
  with_items:
    - python-pip
    - apache2
    - libapache2-mod-shib2

- name: Enable apache2 shibboleth module
  sudo: yes
  command: a2enmod shib2
  notify:
    - restart httpd

- name: Enable apache2 ssl module
  sudo: yes
  command: a2enmod ssl
  notify:
    - restart httpd

# Configure Shiboleth SP
- name: Download federation metadata signing certificate
  when: shibboleth_sp.federation_signer_certificate_url is defined and shibboleth_sp.federation_signer_certificate_url
  sudo: yes
  get_url: url={{ shibboleth_sp.federation_signer_certificate_url }}
           dest=/etc/shibboleth/federation_signer.crt

- name: Create self-signed SSL cert
  sudo: yes
  command: openssl req -new -nodes -x509 -subj "/{{ shibboleth_sp.certificate_subject }}/CN={{ shibboleth_sp.host }}/emailAddress={{ shibboleth_sp.certificate_mail }} " -days 3650 -keyout /etc/shibboleth/{{ shibboleth_sp.host }}.shibboleth.key -out /etc/shibboleth/{{ shibboleth_sp.host }}.shibboleth.crt
           creates=/etc/shibboleth/{{ shibboleth_sp.host }}.shibboleth.key

- name: Setup shibboleth2.xml
  sudo: yes
  template: dest=/etc/shibboleth/shibboleth2.xml
            src=shibboleth2.xml.j2
  notify: restart shibd

- name: Setup shibboleth2 attribute-map.xml
  sudo: yes
  template: dest=/etc/shibboleth/attribute-map.xml
            src=attribute-map.xml.j2
  notify: restart shibd

- name: Enable apache2 default-ssl site
  sudo: yes
  command: a2ensite default-ssl
  notify:
    - restart httpd
