---

# handlers file for shibboleth_sp
- name: restart shibd
  sudo: yes
  service: name=shibd
           state=restarted

- name: restart httpd
  sudo: yes
  service: name=apache2
           state=restarted
